apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummy
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::739561048503:role/eks-iam-role-dummy-sa
---
apiVersion: v1
kind: Pod
metadata:
  name: dummy
  labels:
    app: dummy
spec:
  serviceAccountName: dummy
  containers:
    - name: dummy
      image: amazon/aws-cli
      command: [ "tail", "-f", "/dev/null" ]

