apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::739561048503:role/prod-frontend-schema-eks-sa
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  serviceAccountName: frontend
  containers:
    - name: frontend
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/frontend:2.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::739561048503:role/prod-expense-backend-eks-sa
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  serviceAccountName: backend
  containers:
    - name: backend
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/backend:2.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: schema
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::739561048503:role/prod-expense-schema-eks-sa
---
apiVersion: batch/v1
kind: Job
metadata:
  name: schema
spec:
  template:
    spec:
      serviceAccountName: schema
      restartPolicy: Never
      containers:
      - name: schema
        image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/expense-schema-load:2.0.3
        env:
        - name: COMPONENT
          value: backend


